### ISSUE TITLE
高级火箭的兼容性问题。

### ISSUE THREAD

**Issue by happymy** [CFPAOrg/cfpaorg.github.io#155]
不是翻译错误！！！

采集气体的无人机界面正常应该是这样的：
![2018-10-29_20 00 51](https://user-images.githubusercontent.com/44517078/47830328-65717e80-ddc6-11e8-8fd6-8c3d5cd43be2.png)

加了汉化资源包后：
![2018-11-01_11 21 13](https://user-images.githubusercontent.com/44517078/47830780-686d6e80-ddc8-11e8-8a4e-8fed8c032ffc.png)

这个 选择目的地 按钮，是普通火箭上的，无人机没有的。

**Comment by TartaricAcid** [comment]
这个问题看起来比我想象的严重多了，我需要多花些时间来查找下原因和解决办法

**Comment by TartaricAcid** [comment]
删掉此词条后恢复正常，已修复
