### ISSUE TITLE
Nature's Aura手册电击手册部分内容导致游戏崩溃

### ISSUE THREAD

**Issue by magcicada** [CFPAOrg/cfpaorg.github.io#172]
汉化后Nature's Aura手册中点击装饰方块或者有些部分内容游戏直接崩溃，崩溃报告为Patchouli内容读取错误

**Comment by TartaricAcid** [comment]
最好给个崩溃报告

**Comment by magcicada** [comment]
[https://paste.dimdev.org/tovunususi.mccrash](url) @TartaricAcid 
here you are,这是亲您要的崩溃报告
