### ISSUE TITLE
工业线缆（Industrial Wires）手册汉化超出范围

### ISSUE THREAD

**Issue by luoxingzlx** [CFPAOrg/cfpaorg.github.io#181]
在工程师手册里关于工业线缆部分条目排版错误，部分条目超出手册页面以至于无法正常查看
![snipaste_20181212_192552](https://user-images.githubusercontent.com/44374013/49866851-df743900-fe43-11e8-8478-a3a5f7c065a7.png)
![snipaste_20181212_192634](https://user-images.githubusercontent.com/44374013/49866861-e4d18380-fe43-11e8-9c4d-27f5c29ed551.png)

**Comment by TartaricAcid** [comment]
分页部分属于硬编码，建议直接和 Industrial Wires 原作者反馈相关问题，通过我们这边无法解决
