### ISSUE TITLE
943,又有活儿了（笑），solar flux reborn更新了新东西

### ISSUE THREAD

**Issue by magcicada** [CFPAOrg/cfpaorg.github.io#199]
Solar Flux Reborn这个mod更新了新东西，包括和无尽贪婪联动的新的两个太阳能板和一大堆升级插件，如图：
![2019-01-16_14 26 31](https://user-images.githubusercontent.com/45464670/51230563-61073b80-199b-11e9-8edd-29a09ff32dab.png)

**Comment by TartaricAcid** [comment]
只要是 weblate 所有的项目，无需主动提醒翻译更新，在一星期内爬虫会主动更新所有仓库
