### ISSUE TITLE
请求添加Reasonable Realism模组各分包翻译

### ISSUE THREAD

**Issue by luoxingzlx** [CFPAOrg/cfpaorg.github.io#204]
[Reasonable Realism](https://minecraft.curseforge.com/projects/reasonable-realism)模组已停止更新，但各分包仍在更新
包括[Harder Ores](https://minecraft.curseforge.com/projects/harder-ores)，[Ore Flowers](https://minecraft.curseforge.com/projects/ore-flowers)，[Harder Farming](https://minecraft.curseforge.com/projects/harder-farming)，[Expanded Industry](https://minecraft.curseforge.com/projects/expanded-industry)
均属同一作者

**Comment by TartaricAcid** [comment]
已经添加
