### ISSUE TITLE
CFPA 模组翻译问题反馈页面 点击提交后转至502 badgateway

### ISSUE THREAD

**Issue by BecksIsAlreadyTaken** [CFPAOrg/cfpaorg.github.io#205]
发现了神秘农业的一个物品名称错乱问题

tier 1的下级精华种子 -》中级精华种子

tier 2的初级精华种子 -》终极精华种子

tier 3的中级精华种子 -》初级精华种子

tier 4的高级精华种子 -》下级精华种子 

依次类推，可能是模组的问题，因为我查看了神秘农业的lang文件翻译是正确的

**Comment by TartaricAcid** [comment]
抱歉，是服务器那边重启的锅，现在已经修复

**Comment by TartaricAcid** [comment]
已经修正
