### ISSUE TITLE
Cyclic 饰品tooltip显示错乱

### ISSUE THREAD

**Issue by BecksIsAlreadyTaken** [CFPAOrg/cfpaorg.github.io#206]
带有右键开关的饰品 如 防火饰品
会显示 便携睡袋的 tooltip 

当卸下Minecraft-Mod-Language-Modpack这个资源包时恢复正常

**Comment by BecksIsAlreadyTaken** [comment]
（更正：简易睡袋）

**Comment by BecksIsAlreadyTaken** [comment]
[装载resourcepack后：饰品示例1 御空饰品](https://github.com/BecksIsAlreadyTaken/BecksIsAlreadyTaken.github.io/blob/master/images/with%20resourcepack%201.png)

[装载resoucepack后：饰品示例2 简易睡袋](https://github.com/BecksIsAlreadyTaken/BecksIsAlreadyTaken.github.io/blob/master/images/with%20resourcepack%202.png)

[卸下resourcepack：御空饰品](https://github.com/BecksIsAlreadyTaken/BecksIsAlreadyTaken.github.io/blob/master/images/without%20resourcepack%201.png)

[卸下resoucrepack：简易睡袋](https://github.com/BecksIsAlreadyTaken/BecksIsAlreadyTaken.github.io/blob/master/images/without%20resourcepack%202.png)

测试了一下，貌似不装载1.12.2汉化万用包就不会出问题

**Comment by TartaricAcid** [comment]
你可以试试把 <https://minecraft.curseforge.com/projects/tough-expansion> 这个模组装上，一样会出问题

好吧，不皮了，这就是个重名 key 问题，我给原作者反馈下

**Comment by BecksIsAlreadyTaken** [comment]
我玩的整合是stoneblock，今天看其他玩家的视频的时候，他的cyclic饰品tooltip就是正常的，很奇怪

**Comment by TartaricAcid** [comment]
已经修复

**Comment by BecksIsAlreadyTaken** [comment]
感谢
