### ISSUE TITLE
Cyclic 收割机等功能方块设置作用范围 汉化出错

### ISSUE THREAD

**Issue by BecksIsAlreadyTaken** [CFPAOrg/cfpaorg.github.io#210]
[一图流，左边应该显示几乘几的吧？](https://github.com/BecksIsAlreadyTaken/BecksIsAlreadyTaken.github.io/blob/master/images/2019-01-29_00.10.10.png)

**Comment by TartaricAcid** [comment]
详细说下你用的 cyclic 版本

**Comment by BecksIsAlreadyTaken** [comment]
cyclic-1.12.2-1.17.15

**Comment by TartaricAcid** [comment]
已经修复
