### ISSUE TITLE
极限反应堆翻译无法加载

### ISSUE THREAD

**Issue by magcicada** [CFPAOrg/cfpaorg.github.io#213]
极限反应堆所有条目中文翻译没有加载，全部还原为原版英文，如图
![image](https://user-images.githubusercontent.com/45464670/52349436-83075180-2a61-11e9-84f2-719fdcb39abb.png)顺便提一下，神秘农业附属Mystical Agradditions又新出了一个中子锭种子……，还有无中生有Ex Nihilo: Creatio的beta版本也新出了个橡胶树种子，希望943大大能尽快添加到翻译。

**Comment by TartaricAcid** [comment]
首先，这些模组翻译都是脚本自动更新的，所以无需提醒都会自动加入。

你使用的 Big Reactor 模组没有更新到最新版，上次更新作者全面更换了语言文件的 key，导致旧版本模组失效。
其他你描述的两个翻译都已经完成。

**Comment by magcicada** [comment]
OK，了解
