### ISSUE TITLE
匠魂史莱姆树叶翻译错乱

### ISSUE THREAD

**Issue by magcicada** [CFPAOrg/cfpaorg.github.io#219]
匠魂的史莱姆树叶颜色翻译对应不对，只有树叶是错的，其他都没有问题，如图
![2019-02-10_22 49 48](https://user-images.githubusercontent.com/45464670/52535201-7b5beb80-2d86-11e9-8d0e-a03340811185.png)
![2019-02-10_22 49 46](https://user-images.githubusercontent.com/45464670/52535203-80209f80-2d86-11e9-8a75-447290c80967.png)
![2019-02-10_22 49 43](https://user-images.githubusercontent.com/45464670/52535207-86168080-2d86-11e9-9d0b-32342f6e0a99.png)

**Comment by TartaricAcid** [comment]
处理脚本的问题，原英文都是相同的内容

**Comment by TartaricAcid** [comment]
改好了
