### ISSUE TITLE
无尽贪婪奇点压缩机翻译问题

### ISSUE THREAD

**Issue by magcicada** [CFPAOrg/cfpaorg.github.io#257]
以前奇点压缩机都叫奇点压缩机，现在怎么莫名其妙改城中子态素压缩机了，这是翻译错误还是故意这么翻译的……
![2019-04-02_23 10 48](https://user-images.githubusercontent.com/45464670/55414188-422d4400-559d-11e9-89c3-a205f3156d9b.png)

**Comment by TartaricAcid** [comment]
英文为 `Neutronium Compressor`，没有翻译错误
