### ISSUE TITLE
IC2流体Pahoehoe Lava翻译问题

### ISSUE THREAD

**Issue by magcicada** [CFPAOrg/cfpaorg.github.io#261]
有人把Pahoehoe Lava这个流体进行机翻翻译为了条状熔岩，老版本翻译为熔岩岩浆，希望得到修正
![2019-04-10_18 14 03](https://user-images.githubusercontent.com/45464670/55893997-e3df1180-5beb-11e9-8e69-c70cc2bf8a00.png)

**Comment by TartaricAcid** [comment]
这一处属于正确翻译，你可以查询英文原文
