### ISSUE TITLE
图标处出现双等号

### ISSUE THREAD

**Issue by BecksIsAlreadyTaken** [CFPAOrg/cfpaorg.github.io#309]
[取消加载汉化资源包的时候 双等号就消失了](https://github.com/BecksIsAlreadyTaken/BecksIsAlreadyTaken.github.io/blob/master/images/2019-10-28_21.14.49.png)

**Comment by TartaricAcid** [comment]
有毒，我查下

**Comment by BecksIsAlreadyTaken** [comment]
[如果使用了custommainmenu mod的话，标题界面左下角这个自定义的图标上面也有双等号，不知道是不是我电脑的问题？](https://github.com/BecksIsAlreadyTaken/BecksIsAlreadyTaken.github.io/blob/master/images/2019-11-03_20.48.24.png)

**Comment by BecksIsAlreadyTaken** [comment]
涉及到button的 如button.fan.sound.tooltip=开启或关闭声音 (cyclic的风扇）
或者 tile.preview.button.off=显示范围(cyclic中带有显示范围按钮的机器) 
关于cyclic中的图标出现双等号的目前检测出以上两类（如果图标足够大的话是可以把双等号遮住的，比如tile.redstone.button0=始终工作 cyclic机器gui里的按钮）

**Comment by BecksIsAlreadyTaken** [comment]
另外我突然想起 玩sevtech ages的时候有一个地图叫做antique atlas 上古地图的mod 在里面可以添加一个图标的waypoint 当升级成journey map的时候，原本的带有图标的路径点名字变成了双等号 不知道和这个问题有没有联系

**Comment by BecksIsAlreadyTaken** [comment]
请问酒石酸菌的客户端有这个问题吗？我想排查一下问题在哪

**Comment by TartaricAcid** [comment]
八成是重名 key，这问题无解

**Comment by BecksIsAlreadyTaken** [comment]
car/lang/zh_cn.lang 126 153
df-roads/lang/zh_cn.lang 135
ebwizardry/lang/zh_cn.lang 938
gregtech/lang/zh_cn.lang 2007
metalchests/lang/zh_cn.lang 29 66
scp/lang/zh_cn.lang 164
undergroundbiomes/lang/zh_cn.lang 507
我把以上的双等号都改为了单等号 不知道是不是翻译的小伙伴多写了一个等号？还是说有特殊用途

modularrouters/lang/zh_cn.lang 61
以及这一个，似乎无法改，我替换成了test1

进入游戏后发现图标处的双等号消失了

**Comment by BecksIsAlreadyTaken** [comment]
已测试，与modularrouters的61行无关 所以将除了它以外的双等号改为单等号 问题就解决了

**Comment by BecksIsAlreadyTaken** [comment]
cyberware 39
ebwizardry 1013

已测试与modularrouters无关
以上所有双等号改后，图标显示错误就消失了！

**Comment by BecksIsAlreadyTaken** [comment]
（另以上有几处是多写了一些东西但是没加注释符号，虽然无伤大雅但是强迫症就挑出来了

**Comment by BecksIsAlreadyTaken** [comment]
@TartaricAcid
